version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:ro
      - portainer_data:/data

volumes:
  portainer_data: